services:
  base_ros_image:
    image: base_ros_image
    build:
      context: .
      dockerfile: dockerfiles/base_ros.dockerfile

  bag:
    container_name: bag
    build:
      context: .
      dockerfile: dockerfiles/bag.dockerfile
    entrypoint: ./ros_ws/bag.sh
    volumes:
      - ./resources/bag/:/ros_ws/bag/
    depends_on:
      - vlp16_lidar

  vlp16_lidar:
    container_name: vlp16_lidar
    build:
      context: .
      dockerfile: dockerfiles/vlp16_lidar.dockerfile
    entrypoint: ./ros_ws/vlp16_lidar.sh
