services:
  base_ros_image:
    image: base_ros_image
    build:
      context: .
      dockerfile: dockerfiles/base_ros.dockerfile

  bag:
    container_name: bag
    build:
      context: .
      dockerfile: dockerfiles/bag.dockerfile
    entrypoint: ./ros_ws/bag.sh
    volumes:
      - /dev/shm:/dev/shm
      - ./resources/bag/:/ros_ws/bag/
    depends_on:
      - vlp16_lidar

  vlp16_lidar:
    container_name: vlp16_lidar
    build:
      context: .
      dockerfile: dockerfiles/vlp16_lidar.dockerfile
    entrypoint: ./ros_ws/vlp16_lidar.sh
    volumes:
      - /dev/shm:/dev/shm

  d455_realsense:
    container_name: d455_realsense
    build:
      context: .
      dockerfile: dockerfiles/realsense.dockerfile
    entrypoint: ./ros_ws/d455_realsense.sh
    volumes:
      - /dev/shm:/dev/shm
    privileged: true

  d435_realsense:
    container_name: d435_realsense
    build:
      context: .
      dockerfile: dockerfiles/realsense.dockerfile
    entrypoint: ./ros_ws/d435_realsense.sh
    volumes:
      - /dev/shm:/dev/shm
    privileged: true

  zed2i_stereolabs:
    container_name: zed2i_stereolabs
    build:
      context: .
      dockerfile: dockerfiles/zed2i_stereolabs.dockerfile
    entrypoint: ./ros_ws/zed2i_stereolabs.sh
    volumes:
      - /dev:/dev
      - ./resources/zed/:/usr/local/zed/resources/
    privileged: true
    runtime: nvidia
